pg_replication_user: "{{ lookup('env', 'PG_REPLICATION_USER') }}"
pg_replication_password: "{{ lookup('env', 'PG_REPLICATION_PASSWORD') }}"
pg_username: "{{ lookup('env', 'PG_USERNAME') }}"
pg_password: "{{ lookup('env', 'PG_PASSWORD') }}"
pg_database: "{{ lookup('env', 'PG_DATABASE') }}"
pg_postgres_password: "{{ lookup('env', 'PG_POSTGRES_PASSWORD') }}"
strapi_check_delay: "{{ lookup('env', 'STRAPI_CHECK_DELAY') }}"
strapi_check_retries: "{{ lookup('env', 'STRAPI_CHECK_RETRIES') }}"
vm1_host_ip: "{{ lookup('env', 'VM1_HOST_IP') }}"
vm1_ssh_user: "{{ lookup('env', 'VM1_SSH_USER') }}"
vm1_ssh_key_path: "{{ lookup('env', 'VM1_SSH_KEY_PATH') }}"
