scope: patroni_cluster
name: patroni_node02
namespace: /patroni

restapi:
  listen: 0.0.0.0:8008
  connect_address: patroni_node02:8008

etcd3:
  host: etcd:2379
  protocol: http

watchdog:
  mode: off

postgresql:
  listen: 0.0.0.0:5432
  connect_address: patroni_node02:5432
  use_unix_socket: true
  data_dir: /var/lib/postgresql/data
  bin_dir: /usr/lib/postgresql/17.2/bin
  use_pg_rewind: true
  remove_data_directory_on_diverged_timelines: true
  remove_data_directory_on_rewind_failure: true
  authentication:
    superuser:
      username: postgres
      password: postgres
    replication:
      username: replicator
      password: rep-pass
    rewind:
      username: postgres
      password: postgres
  parameters:
    wal_level: replica
    hot_standby: "on"
    max_wal_senders: 10
    max_replication_slots: 10
    logging_collector: "on"
    wal_log_hints: "on"
  pg_hba:
    - host all all 0.0.0.0/0 md5
    - host replication replicator 0.0.0.0/0 md5
    - host all postgres 0.0.0.0/0 md5
    - local all all trust
  create_replica_methods: ["basebackup"]
  basebackup:
    max-rate: 100M
    checkpoint: fast
