- name: Ensure haproxy config directory exists
  ansible.builtin.file:
    path: /opt/haproxy
    state: directory
    mode: "0755"

- name: Copy haproxy.cfg
  ansible.builtin.copy:
    src: files/haproxy.cfg
    dest: /opt/haproxy/haproxy.cfg
    mode: "0644"

- name: Pull HAProxy image
  community.docker.docker_image:
    name: bitnami/haproxy:latest
    source: pull

- name: Run HAProxy container
  community.docker.docker_container:
    name: haproxy
    image: bitnami/haproxy:latest
    state: started
    restart_policy: always
    volumes:
      - /opt/haproxy/haproxy.cfg:/bitnami/haproxy/conf/haproxy.cfg
    ports:
      - "5432:5432"
      - "8404:8404"
    networks:
      - name: "{{ pg_network }}"

- name: Confirm HAProxy is live
  debug:
    msg: "HAProxy is live at http://{{ hostvars[inventory_hostname].ansible_host }}:8404/stats"
