- name: ⚙️ NODE_02 Ensure Patroni config directory exists
  ansible.builtin.file:
    path: /opt/patroni
    state: directory
    mode: '0755'

- name: ⚙️ NODE_02 Ensure Patroni data directory exists with correct permissions
  ansible.builtin.file:
    path: /opt/postgres-data-node02
    state: directory
    owner: 1000
    group: 1000
    mode: "0700"

- name: ⚙️ NODE_02 Ensure /run/postgresql exists
  ansible.builtin.file:
    path: /run/postgresql
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'

- name: ⚙️ NODE_02 Copy Patroni config file
  ansible.builtin.copy:
    src: files/patroni_node02.yml
    dest: /opt/patroni/patroni02.yml
    mode: '0644'

- name: ⚙️ NODE_02 Run Patroni container
  community.docker.docker_container:
    name: patroni_node02
    image: ongres/patroni:latest
    state: started
    restart_policy: always
    command: ["patroni", "/config/patroni.yml"]
    volumes:
      - /opt/patroni/patroni02.yml:/config/patroni.yml
      - /opt/postgres-data-node02:/var/lib/postgresql/data
      - /run/postgresql:/run/postgresql
    networks:
      - name: "{{ pg_network }}"
