- hosts: vm1
  become: true

  tasks:
    - name: Stop and remove Strapi container
      community.docker.docker_container:
        name: "{{ strapi_container_name }}"
        state: absent
        force_kill: true

    - name: Stop and remove PostgreSQL master container
      community.docker.docker_container:
        name: "{{ pg_master_container_name }}"
        state: absent
        force_kill: true

    - name: Remove PostgreSQL master volume
      community.docker.docker_volume:
        name: "{{ pg_master_volume }}"
        state: absent

    - name: Status
      debug:
        msg: "Cleanup for HW1 completed."
