- name: Create folder
  become: true
  ansible.builtin.file:
    path: "{{ grafana_data_path }}"
    state: "{{ folder_state }}"
    mode: "{{ folder_mode }}"

- name: Copy Grafana config
  ansible.builtin.copy:
    src: "{{ grafana_copy_config_src }}"
    dest: "{{ grafana_copy_config_dest }}"

- name: Copy Grafana dashboard
  ansible.builtin.copy:
    src: "{{ grafana_copy_dashboard_src }}"
    dest: "{{ grafana_copy_dashboard_dest }}"

- name: Run Grafana container
  community.docker.docker_container:
    name: "{{ grafana_container_name }}"
    image: "{{ grafana_image }}"
    restart_policy: "{{ grafana_restart_policy }}"
    env:
      GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
      GF_USERS_ALLOW_SIGN_UP: "{{ grafana_users_allow_sign_up }}"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "{{ grafana_dashboards_default_home_dashboard_path }}"
    ports:
      - "{{ grafana_ports }}"
    volumes:
      - "{{ grafana_volume_path_data }}"
      - "{{ grafana_volume_path_datasource }}"
      - "{{ grafana_volume_path_dashboard }}"
    networks:
      - name: "{{ pg_network }}"

- name: Confirm Grafana is live
  ansible.builtin.debug:
    msg: "Grafana is live at http://{{ hostvars[inventory_hostname].ansible_host }}:3000"
