---
- name: Home work 1
  hosts: carrier

  tasks:
    - name: Display Configuration Variables
      ansible.builtin.debug:
        msg:
          - "wordpress: {{ is_wordpress }}"
          - "strapi_port: {{ strapi_outside_port }}"
          - "strapi_db_name: {{ pg_database }}"
          - "db_host: {{ strapi_database_host }}"
          - "db_pass: {{ pg_postgres_password }}"

  roles:
    - docker
    - pg_master
    - strapi

  post_tasks:
    - name: Waiting for Strapi to become available
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname].ansible_host }}:{{ strapi_port_outside }}"
        method: GET
        status_code: 200
      register: strapi_check
      retries: "{{ strapi_check_retries }}"
      delay: "{{ strapi_check_delay }}"
      until: strapi_check.status == 200

    - name: Confirm Strapi is live
      ansible.builtin.debug:
        msg: "Strapi is live at http://{{ hostvars[inventory_hostname].ansible_host }}:{{ strapi_port_outside }}"
