---
- name: Home work 1
  hosts: carrier

  tasks:
    - name: Display Configuration Variables
      ansible.builtin.debug:
        msg:
          - "wordpress: {{ is_wordpress }}" # True or False
          - "wordpress_port: {{ wordpress_port }}" # 80 or 8080 or whatever
          - "wordpress_db_name: {{ wordpress_db_name }}" # WP database name
          - "db_host: {{ db_host }}" # container name
          - "db_pass: {{ db_pass }}" # root password

  roles:
    - docker
    - pg_cluster_master
    - strapi

  post_tasks:
    - name: Waiting {{ strapi_check_delay }}s for Strapi to become available
      uri:
        url: "http://{{ hostvars[inventory_hostname].ansible_host }}:1337"
        method: GET
        status_code: 200
      register: strapi_check
      retries: "{{ strapi_check_retries }}"
      delay: "{{ strapi_check_delay }}"
      until: strapi_check.status == 200

    - name: Confirm Strapi is live
      ansible.builtin.debug:
        msg: "Strapi is live at http://{{ hostvars[inventory_hostname].ansible_host }}:1337"
