- name: Run cAdvisor container
  community.docker.docker_container:
    name: "{{ cadvisor_container_name }}"
    image: "{{ cadvisor_image }}"
    restart_policy: always
    ports:
      - "{{ cadvisor_ports }}"
    volumes:
      - "{{ cadvisor_volume_path_root }}"
      - "{{ cadvisor_volume_path_var }}"
      - "{{ cadvisor_volume_path_sys }}"
    networks:
      - name: "{{ pg_network }}"

- name: Confirm cAdvisor is live
  debug:
    msg: "cAdvisor is live at http://{{ hostvars[inventory_hostname].ansible_host }}:8080"
