- hosts: vm1
  become: true

  tasks:
    - name: Remove etcd container
      community.docker.docker_container:
        name: etcd
        state: absent
        force_kill: true

    - name: Remove etcd data directory
      ansible.builtin.file:
        path: /opt/etcd/data
        state: absent

    - name: Status
      debug:
        msg: "ETCD and all related resources successfully removed."
