- hosts: carrier

  tasks:
    - name: Stop and remove cAdvisor container
      community.docker.docker_container:
        name: cadvisor
        state: absent
        force_kill: true

    - name: Status
      ansible.builtin.debug:
        msg: "cAdvisor and all related resources successfully removed."
