- hosts: carrier

  roles:
    - monitoring-restart

  post_tasks:
    - name: Wait for Grafana to become available
      uri:
        url: "http://{{ hostvars[inventory_hostname].ansible_host }}:3000"
        method: GET
        status_code: 200
      register: grafana_check
      retries: "{{ strapi_check_retries }}"
      delay: "{{ strapi_check_delay }}"
      until: grafana_check.status == 200

    - name: Confirm Grafana is live
      ansible.builtin.debug:
        msg: "Grafana is live at http://{{ hostvars[inventory_hostname].ansible_host }}:3000"
