---
- name: Install HW2
  hosts: carrier

  roles:
    - pg_replica

  post_tasks:
    - name: Test replication
      ansible.builtin.include_tasks: test.yml

    - name: Status
      ansible.builtin.debug:
        msg: "Replica added. PostgreSQL cluster now has master and slave running."
