- name: Create Docker volume for PostgreSQL master
  community.docker.docker_volume:
    name: "{{ pg_master_volume }}"

- name: Run PostgreSQL master container
  community.docker.docker_container:
    name: "{{ pg_master_container_name }}"
    image: "{{ pg_master_image }}"
    restart_policy: always
    env:
      POSTGRESQL_REPLICATION_MODE: "master"
      POSTGRESQL_REPLICATION_USER: "{{ pg_replication_user }}"
      POSTGRESQL_REPLICATION_PASSWORD: "{{ pg_replication_password }}"
      POSTGRESQL_USERNAME: "{{ pg_username }}"
      POSTGRESQL_PASSWORD: "{{ pg_password }}"
      POSTGRESQL_DATABASE: "{{ pg_database }}"
      POSTGRESQL_POSTGRES_PASSWORD: "{{ pg_postgres_password }}"
    volumes:
      - "{{ pg_master_volume_path }}"
    networks:
      - name: "{{ pg_network }}"
