- name: Create Docker volume for PostgreSQL master
  community.docker.docker_volume:
    name: pg_master_data

- name: Run PostgreSQL master container
  community.docker.docker_container:
    name: postgres_master
    image: bitnami/postgresql:15
    restart_policy: always
    env:
      POSTGRESQL_REPLICATION_MODE: "master"
      POSTGRESQL_REPLICATION_USER: "{{ pg_replication_user }}"
      POSTGRESQL_REPLICATION_PASSWORD: "{{ pg_replication_password }}"
      POSTGRESQL_USERNAME: "{{ pg_username }}"
      POSTGRESQL_PASSWORD: "{{ pg_password }}"
      POSTGRESQL_DATABASE: "{{ pg_database }}"
      POSTGRESQL_POSTGRES_PASSWORD: "{{ pg_postgres_password }}"
    volumes:
      - pg_master_data:/bitnami/postgresql
    networks:
      - name: pg_cluster_net
