- hosts: vm1
  become: true
  tasks:

    - name: Stop and remove Strapi container
      community.docker.docker_container:
        name: strapi
        state: absent
        force_kill: true

    - name: Stop and remove PostgreSQL master container
      community.docker.docker_container:
        name: postgres_master
        state: absent
        force_kill: true

    - name: Stop and remove PostgreSQL replica container
      community.docker.docker_container:
        name: postgres_replica
        state: absent
        force_kill: true

    - name: Remove Strapi volume (if exists)
      community.docker.docker_volume:
        name: strapi_pgdata
        state: absent
      ignore_errors: true

    - name: Remove PostgreSQL master volume
      community.docker.docker_volume:
        name: pg_master_data
        state: absent

    - name: Remove PostgreSQL replica volume
      community.docker.docker_volume:
        name: pg_replica_data
        state: absent

    - name: Remove Docker network for cluster
      community.docker.docker_network:
        name: pg_cluster_net
        state: absent

    - name: Final cleanup message
      debug:
        msg: "Cleanup complete: containers, volume and network removed."
